export const TOGGLE_SELECT = 'TOGGLE_SELECT';
export const REFRESH_POSTS = 'REFRESH_POSTS';
export const REFRESH_POSTS_SUCCESS = 'REFRESH_POSTS_SUCCESS';
export const REFRESH_POSTS_ERROR = 'REFRESH_POSTS_ERROR';
